// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMx0vARE2t0ED7EtFQUJtKx_qLiyzYp3s',
    appId: '1:328158827727:web:b871bd6f1da8301e3153ba',
    messagingSenderId: '328158827727',
    projectId: 'messenger-3e6de',
    authDomain: 'messenger-3e6de.firebaseapp.com',
    storageBucket: 'messenger-3e6de.appspot.com',
    measurementId: 'G-J9CWGPF1WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLA4yGLAKXrIAosoAxiODCUwm8fKXky_0',
    appId: '1:328158827727:android:4a4c9f54b602dc313153ba',
    messagingSenderId: '328158827727',
    projectId: 'messenger-3e6de',
    storageBucket: 'messenger-3e6de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx5JeNPKQ2rWQNooD7-l0HxxV3Ka7sIHc',
    appId: '1:328158827727:ios:16ef8aaf8efd32f63153ba',
    messagingSenderId: '328158827727',
    projectId: 'messenger-3e6de',
    storageBucket: 'messenger-3e6de.appspot.com',
    iosClientId: '328158827727-m8nobnp4krj5e5fjrqqjrrlv5uqn1fc6.apps.googleusercontent.com',
    iosBundleId: 'attano.yukiteru.messenger.messenger',
  );
}
